config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :admins
  resources :products
  root "welcomes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/welcome.rb
class Welcome < ApplicationRecord
  has_one_attached :image
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:firstname,:lastname,:address,:phone])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product=Product.all
  end
  def new
    @product=Product.new
  end
  def create

    @product=Product.new
    @product.name=params[:product][:name]
    @product.product_desc=params[:product][:product_desc]
    @product.size=params[:product][:size]
    @product.colour=params[:product][:colour]
    @product.price=params[:product][:price]
    @product.image=params[:product][:image]

    if @product.save
      flash[:notice]="Product added Successfully"
      redirect_to @product

    else
      render :new
    end


  end
  def show
    @product=Product.find(params[:id])
  end

  def edit
    @product=Product.find(params[:id])
  end
  def update
    @product=Product.find(params[:id])
    @product.name=params[:name]
    @product.product_desc=params[:product][:product_desc]
    @product.size=params[:product][:size]
    @product.colour=params[:product][:colour]
    @product.price=params[:product][:price]
    @product.image=params[:product][:image]
    if @product.save
      redirect_to @product
    end
  end

  def destroy
    @product=Product.find(params[:id])
    @product.destroy
    redirect_to @product
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user=User.all
  end
  def allusers
    @user=User.all
  end
  def show
    @user=User.find(params[:id])
  end
  def destroy
    @user=User.find(params[:id])
    if @user.destroy
      flash[:notice]="User is deleted Successfully"
      redirect_to @user
    end
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    @product=Product.all

  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/products/_forms.html.erb
<%=render "products/forms" %>

app/views/products/edit.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :product_desc %>
  <%= f.input :size %>
  <%= f.input :colour %>
  <%= f.input :price %><br>
  <%= f.file_field :image, class: "form-field" %>
  <%= f.submit :Update,class:"btn btn-info" %>


<% end %>

app/views/products/index.html.erb
<h1>All products</h1>
<% @product.each do |product| %>

  <div class="card" style="width: 30rem;height:40rem;float:left;">
    <%if product.image.attached?%>
      <%= image_tag product.image,class:"card-img-top",style: 'height:420px;width:auto;'%>
    <% end %>
    <div class="card-body">
      <h5 class="card-title">Product-Name:<%= product.name%></h5>
      <p class="card-text"><h3>Description:</h3><%= product.product_desc%>.</p>
      <h6>Colour:<%= product.colour%></h6>
      <h6>Size:<%= product.size%></h6>
      <h6>Price:<%= product.price%></h6>
      <%=link_to"View Details",product_path(product),class:"btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :product_desc %>
  <%= f.input :size %>
  <%= f.input :colour %>
  <%= f.input :price %><br>
  <%= f.file_field :image, class: "form-field" %>
  <%= f.submit :Addproduct,class:"btn btn-success" %>


<% end %>

app/views/products/show.html.erb
<div class="card-body">
  <h5 class="card-title">Product-Name:<%= @product.name%></h5>
  <p class="card-text"><h3>Description:</h3><%= @product.product_desc%>.</p>
  <h6>Colour:<%=@product.colour%></h6>
  <h6>Size:<%= @product.size%></h6>
  <h6>Price:<%= @product.price%></h6>
  <%=link_to "Edit" ,edit_product_path(@product),class:"btn btn-warning"%>
  <%=button_to"Delete" ,product_path(@product), method: :delete,class:"btn btn-danger"%>










  <%if current_user.has_role?"admin"%>
  <%=link_to"Dashbord",admins_path,class:"btn btn-info" %>
    <%end%>
</div>

app/views/users/_allusers.html.erb
<table class="table table-dark">
  <thead>
  <tr>
    <th scope="col">First-Name</th>
    <th scope="col">Last-Name</th>
    <th scope="col">Address</th>
    <th scope="col">Phone-Number</th>
    <th scope="col">Email</th>
    <th scope="col">Details</th>


  </tr>
  </thead>
  <%@user.each do |user|%>

    <tbody>
    <tr>
      <td><%=user.firstname %></td>
      <td><%=user.lastname %></td>
      <td><%=user.address %></td>
      <td><%=user.phone %></td>
      <td><%=user.email %></td>
      <td><%=link_to"View Details",user_path(user),class:"btn btn-primary"%></td>
    </tr>

    </tbody>
  <%end %>
</table>

app/views/users/index.html.erb
<h1>All users</h1>

  <%=button_to "Sign-out",destroy_user_session_path,method: :delete,class: "btn btn-danger"%></h1>
 <%=render "users/allusers" %>

app/views/users/show.html.erb
  <h1>User Details</h1>
  <table class="table table-dark">
    <thead>
    <tr>
      <th scope="col">First-Name</th>
      <th scope="col">Last-Name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone-Number</th>
      <th scope="col">Email</th>
      <th scope="col"></th>

    </tr>
    </thead>
    <tr>
  <td><%=@user.firstname %></td>
  <td><%=@user.lastname %></td>
  <td><%=@user.address %></td>
  <td><%=@user.phone %></td>
  <td><%=@user.email %></td>
   <td><%=button_to"Delete",user_path(@user),method: :delete ,class:"btn btn-danger"%></td>

    </tr>
  </table>

app/views/welcomes/index.html.erb
<h1>Home</h1>

<%if user_signed_in?%>
  <%if current_user.has_role?"admin"%>
    <%controller.redirect_to admins_path %>
  <%end %>
  <%=button_to "Sign-out",destroy_user_session_path,method: :delete,class: "btn btn-danger"%>
  <% @product.each do |product| %>

    <div class="card" style="width: 30rem;height:40rem;float:left;">
      <%if product.image.attached?%>
        <%= image_tag product.image,class:"card-img-top",style: 'height:420px;width:auto;'%>
      <% end %>
      <div class="card-body">
        <h5 class="card-title">Product-Name:<%= product.name%></h5>
        <p class="card-text"><h3>Description:</h3><%= product.product_desc%>.</p>
        <h6>Colour:<%= product.colour%></h6>
        <h6>Size:<%= product.size%></h6>
        <h6>Price:<%= product.price%></h6>

        <a href="#" class="btn btn-primary">Add to cart</a>
      </div>
    </div>


  <% end %>


<%else%>
     <%=button_to"Sign-in",user_session_path ,class: "btn btn-success"%>
<%end %>